---
- hosts: docker
  remote_user: docker
  gather_facts: false
  vars:
    image_name: react_app
    container_name: web_app
  tasks:
    # - name: Creating Temporary image
    #   docker_image:
    #     name: "{{ image_name }}"
    #     repository: "temp"
    #     push: false
    #     source: local

    - name: Deleting Containers
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: absent

    - name: Creating Temporary Container
      docker_container:
        name: "temp"
        image: "temp"
        ports:
          - "8080:80"
        state: present

    - name: Deleting Old Image
      docker_image:
        name: "{{ image_name }}"
        state: absent

    - name: Building Docker Image
      docker_image:
        name: "{{ image_name }}"
        source: build
        build:
          path: "{{ repo_dest }}"
          pull: no
        state: present
      register: docker_build_result
    - name: Print Docker Build Result
      debug:
        var: docker_build_result

    - name: Deleting Temporary Container
      docker_container: 
        name: "temp"
        image: "temp"
        state: absent
      
    - name: Running Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        ports:
          - "8080:80"
        state: started

    - name: Deleting Temporary Image
      docker_image:
        name: "temp"
        state: absent
    
    - name: Deleting the build files
      file:
        path: "{{ repo_dest }}"
        state: absent

    - name: Deleting Dangling Images
      community.docker.docker_prune:
        images: yes
