---
- hosts: docker
  remote_user: docker
  gather_facts: false
  vars:
    image_name: react_app
    container_name: web_app
    repo_dest: /home/docker/project/files
    current_tag: "{{ '1.' + version }}"
    previous_tag: "{{ ':1.' + previous }}"
  tasks:

    - name: Building Docker Image
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ current_tag }}"
        source: build
        build:
          path: "{{ repo_dest }}"
          pull: no
        state: present

    - name: Deleting Containers
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name + previous_tag }}"
        state: absent

    - name: Running Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name + ':' + current_tag }}"
        ports:
          - "80:80"
        state: started

    - name: Deleting Old Image
      docker_image:
        name: "{{ image_name + previous_tag }}"
        state: absent

    - name: Deleting the build files
      file:
        path: "{{ repo_dest }}"
        state: absent

    - name: Deleting Dangling Images
      community.docker.docker_prune:
        images: yes
