---
- hosts: docker
  remote_user: docker
  gather_facts: false
  vars:
    github_repo: https://github.com/hussain1406/TextUtils.git
    repo_dest: /home/docker/project/files
  tasks:
    - name: Copy files to Docker Server
      git:
        repo: "{{ github_repo }}"
        dest: "{{ repo_dest }}"
    - name: Copying ansible-deployment.yml file
      ansible.builtin.fetch:
        src: /home/docker/project/files/ansible-deployment.yml
        dest: /home/ansible/project/
        flat: true